
pebble:
  suffix: .html
logging:
  file:
    path: logs
  level:
    com:
      site:
        blog: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.site.blog.entity
server:
  port: 2801
spring:
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: 123456
    username: 123456@qq.com
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          timeout: 20000
          host: smtp.qq.com
          port: 587
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  thymeleaf:
#    cache: false
#    encoding: utf-8
#    mode: HTML
#    suffix: .html

myblog:
  name: 我的博客
  version: 1.0.1
  site:
    ip: http://localhost:2801/

  upload:
    file-url: ${user.home}/.myblog/upload/
    file-prefix: upload/


    avatar: ${user.home}/.myblog/authorImg/
